server:
  port: 8082
spring:
  main:
    allow-bean-definition-overriding: true
  shardingsphere:
    sharding:
      tables:
        user:
          actual-data-nodes: master.user
          key-generator:
            column: id
            type: SNOWFLAKE
            props:
              worker:
                id: 123456
    masterslave:
      name: ms
      master-data-source-name: master
      slave-data-source-names: slave0,slave1
      load-balance-algorithm-type: round_robin
    props:
      sql:
        show: true
    datasource:
      names: master,slave0,slave1
      master:
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://192.168.0.120:3307/t1?characterEncoding=utf-8
        password: root
        type: com.zaxxer.hikari.HikariDataSource
        username: root
      slave0:
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://192.168.0.120:3308/t1?characterEncoding=utf-8
        password: root
        type: com.zaxxer.hikari.HikariDataSource
        username: root
      slave1:
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://192.168.0.120:3309/t1?characterEncoding=utf-8
        password: root
        type: com.zaxxer.hikari.HikariDataSource
        username: root
    orchestration:
      name: zk-sharding
      overwrite: false
      registry:
        namespace: orchestration-sharding
        server-lists: 192.168.0.120:2181
        type: zookeeper

